import { access,copyFile,mkdir,mkdtemp,readFile,rename,rm,writeFile } from 'node:fs/promises'
import { constants } from 'node:fs'; import { basename,dirname,join,resolve } from 'node:path'
import type { DeviceProfile } from '../../shared/domain/device-profile'; import type { ExportLog,ExportResult } from '../../shared/domain/export-result'
import { parseManifest } from '../../shared/services/manifest-parser'; import { validatePackage } from '../../shared/services/package-validator'; import { validateDeviceCompatibility } from '../../shared/services/device-compatibility-validator'; import { calculateSha256 } from '../../shared/services/checksum-service'
export async function exportPackage(source:string,target:string,profile:DeviceProfile,now=new Date()):Promise<ExportResult>{
 try { await access(target,constants.W_OK); const manifest=parseManifest(await readFile(join(source,'manifest.json'),'utf8')); const validation=await validatePackage(source,manifest,now); const size=validation.files.reduce((n,f)=>n+(f.exists?1:0),0); if(validation.status==='failed'||validateDeviceCompatibility(manifest,profile,size).status==='failed') return {kind:'failed',message:'Package validation or compatibility failed.'}
  const destination=resolve(target,...profile.requiredRootFolder.split('/')); const parent=dirname(destination); await mkdir(parent,{recursive:true}); const stage=await mkdtemp(join(parent,`.${basename(destination)}.stage-`)); const files=[]
  try { await copyFile(join(source,'manifest.json'),join(stage,'manifest.json')); for(const f of manifest.files){ if(!validation.files.find(v=>v.path===f.path)?.exists){files.push({path:f.path,status:'skipped' as const});continue}; const out=join(stage,...f.path.split('/')); await mkdir(dirname(out),{recursive:true}); await copyFile(join(source,...f.path.split('/')),out); const hash=await calculateSha256(out); if(hash!==f.sha256.toLowerCase()) throw new Error(`Post-export checksum mismatch: ${f.path}`); files.push({path:f.path,status:'copied' as const,expectedSha256:f.sha256.toLowerCase(),exportedSha256:hash}) }
   const log:ExportLog={schemaVersion:1,packageId:manifest.packageId,profileId:profile.id,exportedAt:now.toISOString(),files}; await writeFile(join(stage,'export-log.json'),JSON.stringify(log,null,2)); await rm(destination,{recursive:true,force:true}); await rename(stage,destination); return {kind:'success',destination,logPath:join(destination,'export-log.json'),files}
  } catch(error){await rm(stage,{recursive:true,force:true});throw error}
 } catch(error){return {kind:'failed',message:error instanceof Error?error.message:'Export failed.'}}
}
